### ISSUE TITLE
Latest update not deployed?

### ISSUE THREAD

**Issue by willyrk1** [gwwar/z-context#14]
It looks like the latest fix for position: sticky was never deployed to the Chrome Web Store.  Is there a reason?  (That bug just burned me so I came here, only to find out it was already reported and allegedly fixed).

Thanks.

**Comment by gwwar** [comment]
Sorry for the delay, I must have forgotten to publish the sticky fix. The latest 1.10.0 is available that includes the position stick fix along with some other changes.
