### ISSUE TITLE
Firefox Version

### ISSUE THREAD

**Issue by JoaquimEsteves** [gwwar/z-context#15]
Hullo,

First of all, let me thank you profusely for such a lovely extension!

Is there anyway I could convince you to develop a similar extension for Firefox?

**Comment by y1n0** [comment]
You can simply load this extension Firefox and it'll work.

Clone this repo and open Firefox and go to `about:debugging#/runtime/this-firefox` page. Click Load Temporary Add-on and select the `manifest.json` file within the folder of this repo.

**Comment by JoaquimEsteves** [comment]
Fantastic! Thank you so much for your reply.
