### ISSUE TITLE
Update stacking context detection to April 2021

### ISSUE THREAD

**Issue by sanoodles** [gwwar/z-context#16]
Hi and thank you very much for this extension.

I've now reviewed https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context and noticed some fancy new stuff is not yet ported to z-context. Please find the list below. Maybe this ticket can be used as "milestone".

    ✅ Root element of the document (<html>).
    ✅ Element with a position value absolute or relative and z-index value other than auto.
    ✅ Element with a position value fixed or sticky (sticky for all mobile browsers, but not older desktop).
    ✅ Element that is a child of a flex container, with z-index value other than auto.
    ❌ Element that is a child of a grid container, with z-index value other than auto.
    ✅ Element with a opacity value less than 1 (See the specification for opacity).
    ✅ Element with a mix-blend-mode value other than normal.
    Element with any of the following properties with value other than none:
        ✅ transform
        ✅ filter
        ✅ perspective
        ❌ clip-path
        ❌ mask / mask-image / mask-border
    ✅ Element with a isolation value isolate.
    ✅ Element with a -webkit-overflow-scrolling value touch.
    ✅ Element with a will-change value specifying any property that would create a stacking context on non-initial value (see this post).
    ❌ Element with a contain value of layout, or paint, or a composite value that includes either of them (i.e. contain: strict, contain: content).

**Comment by gwwar** [comment]
Thanks for the reminder! I've fixed this in #18 and pushed out an extension update for review.
