### ISSUE TITLE
`z-index` in `style` not detected

### ISSUE THREAD

**Issue by tmlmt** [gwwar/z-context#27]
I have this issue where `z-index` is shown as `auto` while element inspection shows that there is a `z-index` property set-up in the `style` attribute of the element. See example below. 

![image](https://user-images.githubusercontent.com/10244927/236559368-ab5fd02e-fd30-4cb4-bd2c-a60b50331152.png)

Environment: 
- Ungoogled Chromium: v112.0
- z-context: v2.1.0
- UI: PrimeVue 
- Nuxt 3 Application

**Comment by gwwar** [comment]
Did this element have a position attribute? z-index won't apply without it.

If it did sometime the container script doesn't correctly register with the devpanel. If it looks stuck you can close and re-open devtools.

Going to close this one out for now, but feel free to send an example page if you still see this.
