### ISSUE TITLE
There is no tab z-index in Chrome

### ISSUE THREAD

**Issue by linux019** [gwwar/z-context#8]
Installed the extension and nothing here as on the image
https://camo.githubusercontent.com/667642c7439c98dc49ec21a3243a1ea13986056b/68747470733a2f2f636c6475702e636f6d2f5569766c5638694a35712e676966

**Comment by gwwar** [comment]
@devbazilio Are you still having trouble? You can check in chrome://extensions/ to see if the extension is enabled. After that it's available in the dev console > Elements > Z-Index (right most option) 

In smaller screens extra tabs are hidden by a chevron:
<img width="363" alt="screen shot 2018-02-17 at 5 34 47 pm" src="https://user-images.githubusercontent.com/1270189/36347289-baa6929c-1408-11e8-88db-4fa831a9f78a.png">

**Comment by linux019** [comment]
It seems that was some bug in chrome, on some sites the tab is shown and on other sites there is no tab. Update to last version solved the issue
